<?xml version="1.0" encoding="UTF-8"?>
<workflowmodel:root xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:workflowmodel="http://workflowmodel">
  <user id="593bbe2d-c876-4ae1-a2c0-9ae9cd28a9ea" name="Samuel Adamson" mail="samuel.adamson@example.com"
      langocde="en" uid="7" roles="./model/workflowsmeta.ecore#//@role.1 ./model/workflowsmeta.ecore#//@role.4 ./model/workflowsmeta.ecore#//@role.3"
      timezone="UTC" status="true"/>
  <role id="7d1b1e72-21c1-40d8-bf67-476723b04667" label="Anonymous user" drupal_internal__id="anonymous"/>
  <role id="cf443d95-8b29-4e92-9751-37ffefb8fc24" label="Administrator" drupal_internal__id="administrator"/>
  <role id="58732b86-87e5-4b5c-908f-28614793203e" label="Authenticated user" drupal_internal__id="authenticated"/>
  <role id="2f18b2a5-7726-4ba9-9f9b-fdbfba4f6f1b" label="Author" drupal_internal__id="author"
      permissions="./model/workflowsmeta.ecore#//@permission.3"/>
  <role id="4dada3fb-5866-4473-bf62-641aae47df59" label="Editor" drupal_internal__id="editor"
      permissions="./model/workflowsmeta.ecore#//@permission.0 ./model/workflowsmeta.ecore#//@permission.1 ./model/workflowsmeta.ecore#//@permission.2 ./model/workflowsmeta.ecore#//@permission.4"/>
  <permission permission_code="use editorial transition archive"/>
  <permission permission_code="use editorial transition archived_draft"/>
  <permission permission_code="use editorial transition archived_published"/>
  <permission permission_code="use editorial transition create_new_draft"/>
  <permission permission_code="use editorial transition publish"/>
  <workflow workflow_code="editorial" label="Editorial" langocde="en" status="true">
    <states label="Archived" default_revision="true" code="archived" weight="5"/>
    <states label="Draft" code="draft" weight="-5"/>
    <states label="Published" default_revision="true" code="published" published="true"/>
    <transitions code="archive" label="Archive" weight="2" from="./model/workflowsmeta.ecore#//@workflow.0/@states.2"
        to="./model/workflowsmeta.ecore#//@workflow.0/@states.0"/>
    <transitions code="archived_draft" label="Restore to Draft" weight="3" from="./model/workflowsmeta.ecore#//@workflow.0/@states.0"
        to="./model/workflowsmeta.ecore#//@workflow.0/@states.1"/>
    <transitions code="archived_published" label="Restore" weight="4" from="./model/workflowsmeta.ecore#//@workflow.0/@states.0"
        to="./model/workflowsmeta.ecore#//@workflow.0/@states.2"/>
    <transitions code="create_new_draft" label="Create New Draft" from="./model/workflowsmeta.ecore#//@workflow.0/@states.1 ./model/workflowsmeta.ecore#//@workflow.0/@states.2"
        to="./model/workflowsmeta.ecore#//@workflow.0/@states.1"/>
    <transitions code="publish" label="Publish" weight="1" from="./model/workflowsmeta.ecore#//@workflow.0/@states.1 ./model/workflowsmeta.ecore#//@workflow.0/@states.2"
        to="./model/workflowsmeta.ecore#//@workflow.0/@states.2"/>
  </workflow>
</workflowmodel:root>
