package edu.uoc.som.cmsdiscover.generator;

import org.eclipse.xtend2.lib.StringConcatenation;

@SuppressWarnings("all")
public class TestsTemplate {
  public CharSequence getTest() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package generated.middleware.Umami_Food_Magazine_API___JSON_API;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import generated.middleware.Umami_Food_Magazine_API___JSON_API.drivers.SearchQuery;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import java.util.List;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("public class mainTest {");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public static void main(String[] args) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("Recipe recipe = new Recipe();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("// Search Feature");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("List<Recipe> fullSearch = recipe.search(new SearchQuery());");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("System.out.println(fullSearch.get(3).getTitle());");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("// Search with Filters");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("List<Recipe> filteredSearch = recipe.search(new SearchQuery().addFilter(\"field_cooking_time\", \"30\"));");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("System.out.println(filteredSearch.get(0).getTitle());");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("// Search Single");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("Recipe singleRecipe = recipe.getSingle(fullSearch.get(1).getUuid());");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("System.out.println(singleRecipe.getTitle());");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("// Navigation");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("List<Tags> tags = singleRecipe.getFieldTags();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("tags.forEach((tag) ->{");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("System.out.println(tag.getName());");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("});");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("System.out.println(\"Final\");");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    return _builder;
  }
}
